### ISSUE TITLE
抓取时机械臂无法够到物体

### ISSUE THREAD

**Issue by Soengseon972** [sebuaa2019/Team103#3]
尝试抓取正常高度桌子上，离桌边5cm的黄色饮料瓶，发现机械臂的运动过程正常，但多次尝试均无法够到物体。

**Comment by EurusQF** [comment]
原因：ROS 环境中抓取相关服务包“wpb_home\wpb_home_bringup”中 的 抓 取 参 数 “ .\config\wpb_home.yaml ” 文 件 中 原 本 参 数 设 置 为“grab_y_offset: 0.0；grab_lift_offset: 0.0；grab_forward_offset: 0.0”不符合抓取的实际情况。
解决：对“wpb_home\wpb_home_bringup\config\wpb_home.yaml”中相 关 参 数 进 行 修 改 ， 修 改 后 的 参 数 设 置 为 “ grab_y_offset: 0.0 ；grab_lift_offset: 0.3；grab_forward_offset: 0.15”。

team103_alpha/wpb_home/wpb_home_bringup/config/wpb_home.yaml

**Comment by EurusQF** [comment]
[team103_alpha/wpb_home/wpb_home_bringup/config/wpb_home.yaml](url)

**Comment by EurusQF** [comment]
[https://github.com/sebuaa2019/Team103/blob/1522cd8d6fdf4b8b1d3cb9e6f2139761e6b3461e/team103_alpha/wpb_home/wpb_home_bringup/config/wpb_home.yaml](url)

**Comment by EurusQF** [comment]
[github.com/sebuaa2019/Team103/blob/1522cd8d6fdf4b8b1d3cb9e6f2139761e6b3461e/team103_alpha/wpb_home/wpb_home_bringup/config/wpb_home.yaml](url)

**Comment by Soengseon972** [comment]
> 原因：ROS 环境中抓取相关服务包“wpb_home\wpb_home_bringup”中 的 抓 取 参 数 “ .\config\wpb_home.yaml ” 文 件 中 原 本 参 数 设 置 为“grab_y_offset: 0.0；grab_lift_offset: 0.0；grab_forward_offset: 0.0”不符合抓取的实际情况。
> 解决：对“wpb_home\wpb_home_bringup\config\wpb_home.yaml”中相 关 参 数 进 行 修 改 ， 修 改 后 的 参 数 设 置 为 “ grab_y_offset: 0.0 ；grab_lift_offset: 0.3；grab_forward_offset: 0.15”。
> 
> team103_alpha/wpb_home/wpb_home_bringup/config/wpb_home.yaml
0.15刚刚好！谢谢大佬
