### ISSUE TITLE
机器人抓取异常处理部分代码逻辑错误

### ISSUE THREAD

**Issue by EurusQF** [sebuaa2019/Team103#4]
机器人抓取异常处理部分代码逻辑错误，将连续的抓取成功判断循环提前切断，导致抓取进程刚刚开启，还未检测到平面和物体就被迫中止。

**Comment by L-Richard** [comment]
[https://github.com/sebuaa2019/Team103/blob/master/team103V3.0/src/init.cpp](url)

**Comment by EurusQF** [comment]
对“\team103\src\exception_handler.cpp”中相关逻辑进行修改，不再提前终止判断循环。
