### ISSUE TITLE
启动联网问题

### ISSUE THREAD

**Issue by sqbuaa** [sebuaa2019/Team103#5]
机器人雷达只有在连接TP-Link-Robot无线网时才能启动，但是在此情况下语音模块无法连到外网正常工作，之前并未出现此种情况。

**Comment by Soengseon972** [comment]
经检测，有其他组同学在机载电脑环境中硬编码机器人IP
`export ROS_IP=xxxx`
将`~/.bashrc`中此行删掉即可

**Comment by Chen-Qixian** [comment]
你检查一下是不有人硬编码IP了，我记得助教在群里说过

**Comment by sqbuaa** [comment]
问题已解决。
