### ISSUE TITLE
机器人启动后雷达无法使用

### ISSUE THREAD

**Issue by Chen-Qixian** [sebuaa2019/Team103#6]
为啥我启动了运行脚本，Rviz界面也显示了，但是rplidar脚本无法正常启动，机器人底盘红外雷达无法正常工作呢？

**Comment by Soengseon972** [comment]
你确定底盘开关开了吗？

**Comment by Chen-Qixian** [comment]
> 你确定底盘开关开了吗？

我确定打开了底盘电源，控制台不报错。知识Rviz界面左侧功能导航栏中显示雷达无法正常工作。

**Comment by Soengseon972** [comment]
> > 你确定底盘开关开了吗？
> 
> 我确定打开了底盘电源，控制台不报错。知识Rviz界面左侧功能导航栏中显示雷达无法正常工作。

试试把QueueSize调大 调成200试试

**Comment by Chen-Qixian** [comment]
好的，问题已解决，谢谢~
