### ISSUE TITLE
机械臂行为异常

### ISSUE THREAD

**Issue by sqbuaa** [sebuaa2019/Team103#8]
抓取前机械臂有开合，但表现很奇怪，不是正常90度打开。

**Comment by Soengseon972** [comment]
能否详细地描述一下机械臂的行为呢？

**Comment by sqbuaa** [comment]
大概是机械臂向上转到跟机器人躯干呈40度角之后机械爪就合上了，然后语音播报说“Got it”就返回了。

**Comment by Soengseon972** [comment]
> 大概是机械臂向上转到跟机器人躯干呈40度角之后机械爪就合上了，然后语音播报说“Got it”就返回了。

线接反了，现在已经可以正常使用

**Comment by sqbuaa** [comment]
好的。
