### ISSUE TITLE
语音控制听不到“噔噔噔”的提示音

### ISSUE THREAD

**Issue by Chen-Qixian** [sebuaa2019/Team103#9]
为啥我在进行语音测试时，听不到开始录音的“噔噔噔”提示音呢？

**Comment by Soengseon972** [comment]
机载电脑上的语音包版本不适配，更换为Ubuntu14.04的语音包之后，能听到“噔噔噔”的提示音。

**Comment by Chen-Qixian** [comment]
嗯，请问有修改代码可以发一份么

**Comment by Soengseon972** [comment]
commit id: 43f0b34e3e6ea0e09c8e8ab5afde692c2a7650c6

**Comment by Chen-Qixian** [comment]
好的，感谢。
